---
output: github_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-")

```
# maposm

## Install
```{r, eval=FALSE}
install.packages("maposm", repos = "https://riatelab.r-universe.dev")
```

## Example
This is a basic example which shows you how to solve a common problem:

```{r example}
library(sf)
library(maposm)
library(mapsf)

castries <- get_city(x = c(-60.990260, 14.009623), r = 2000)
mf_map(castries$zone, col = "#f2efe9", border = NA, add = FALSE)
mf_map(castries$urban, col = "#e0dfdf", border = "#e0dfdf", lwd = .5, add = TRUE)
mf_map(castries$green, col = "#c8facc", border = "#c8facc", lwd = .5, add = TRUE)
mf_map(castries$water, col = "#aad3df", border = "#aad3df", lwd = .5, add = TRUE)
mf_map(castries$railway, col = "grey50", lty = 2, lwd = .2, add = TRUE)
mf_map(castries$road, col = "white", border = "white", lwd = .5, add = TRUE)
mf_map(castries$street, col = "white", border = "white", lwd = .5, add = TRUE)
mf_map(castries$building, col = "#d9d0c9", border = "#c6bab1", lwd = .5, add = TRUE)
mf_map(castries$zone, col = NA, border = "#c6bab1", lwd = 4, add = TRUE)
mf_credits(txt = "\ua9 OpenStreetMap contributors")
mf_scale(size = 500, scale_units = "m")
mf_title("Castries, Saint Lucia")
```


```{r example2}
m <- mapsf::mf_get_mtq()[1, ]
ajoupa <- get_city(x = m)
mf_map(ajoupa$zone, col = "#f2efe9", border = NA, add = FALSE)
mf_map(ajoupa$urban, col = "#e0dfdf", border = "#e0dfdf", lwd = .5, add = TRUE)
mf_map(ajoupa$green, col = "#c8facc", border = "#c8facc", lwd = .5, add = TRUE)
mf_map(ajoupa$water, col = "#aad3df", border = "#aad3df", lwd = .5, add = TRUE)
mf_map(ajoupa$railway, col = "grey50", lty = 2, lwd = .2, add = TRUE)
mf_map(ajoupa$road, col = "white", border = "white", lwd = .5, add = TRUE)
mf_map(ajoupa$street, col = "white", border = "white", lwd = .5, add = TRUE)
mf_map(ajoupa$building, col = "#d9d0c9", border = "#c6bab1", lwd = .5, add = TRUE)
mf_map(ajoupa$zone, col = NA, border = "#c6bab1", lwd = 4, add = TRUE)
mf_credits(txt = "\ua9 OpenStreetMap contributors")
mf_scale(size = 500, scale_units = "m")
mf_title("L'Ajoupa-Bouillon, Martinique")
```


```{r example3}
roseau <- st_as_sf(data.frame(lat = 15.300, lon = -61.388), 
                   coords = c("lon", "lat"), 
                   crs = "EPSG:4326") |>
  st_transform("EPSG:3857") |>
  st_buffer(dist = 500, nQuadSegs = 2) |> 
  get_city()
mf_map(roseau$zone, col = "#f2efe9", border = NA, add = FALSE)
mf_map(roseau$urban, col = "#e0dfdf", border = "#e0dfdf", lwd = .5, add = TRUE)
mf_map(roseau$green, col = "#c8facc", border = "#c8facc", lwd = .5, add = TRUE)
mf_map(roseau$water, col = "#aad3df", border = "#aad3df", lwd = .5, add = TRUE)
mf_map(roseau$railway, col = "grey50", lty = 2, lwd = .2, add = TRUE)
mf_map(roseau$road, col = "white", border = "white", lwd = .5, add = TRUE)
mf_map(roseau$street, col = "white", border = "white", lwd = .5, add = TRUE)
mf_map(roseau$building, col = "#d9d0c9", border = "#c6bab1", lwd = .5, add = TRUE)
mf_map(roseau$zone, col = NA, border = "#c6bab1", lwd = 4, add = TRUE)
mf_credits(txt = "\ua9 OpenStreetMap contributors")
mf_scale(size = 100, scale_units = "m")
mf_title("Roseau, Dominique")
```


